networks:
  app_network:

services:
  backend:
    build: .
    container_name: payment_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: