networks:
  app_network:

services:
  backend:
    build: .
    container_name: payment_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "nodemon", "--watch", "src", "--exec", "ts-node", "src/server.ts"]

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: