name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd paymentcollection_backend && git pull
            sudo npm install
            sudo npm run build
            sudo docker compose down
            sudo docker compose up -d --build
            sudo docker exec -i payment_backend npx sequelize-cli db:migrate